feat: 完成deepin-downloader这个项目的合规性整改
linuxdeepin/deepin-downloader pull request #45
Opened 2022-09-08 09:26 UTC by caimc123456

完成deepin-downloader这个项目的合规性整改

Log:
Task: https://pms.uniontech.com/task-view-184497.html

2022-09-08 13:02 UTC, BLumia commented on .reuse/dep5
> +
```suggestion
```

2022-09-08 13:03 UTC, BLumia commented on .reuse/dep5
> +Files: translations/*  translations/desktop/* translations/downloader/* .tx/*
```suggestion
Files: translations/* translations/desktop/* translations/downloader/* .tx/* 
```

2022-09-09 05:18 UTC, BLumia commented on debian/source/format
> +3.0 (natiav)
native

2022-09-09 06:46 UTC, caimc123456 commented on debian/source/format
> +3.0 (natiav)
fix: 开源整改 -修改format

修改quilt为natiav

Log: 开源整改编译错误处理

2022-09-09 07:48 UTC, BLumia requested changes

2022-09-09 07:48 UTC, BLumia commented on .reuse/dep5
> +License: CC-BY-4.0
CC-BY 是署名，署名署给 None 是不对的吧？

2022-09-09 08:04 UTC, BLumia approved these changes

2022-09-09 08:05 UTC, merged